I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/Harry Potter and the Goblet of Fire/brawl_about_true_hogwarts_champion.rpy", line 45, in script
    drco "Want one, Granger?"
Exception: Sayer 'drco' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/Harry Potter and the Goblet of Fire/brawl_about_true_hogwarts_champion.rpy", line 45, in script
    drco "Want one, Granger?"
  File "/Applications/renpy-8.3.7-sdk/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/Applications/renpy-8.3.7-sdk/renpy/ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-8.3.7-sdk/renpy/ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'drco' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.7.25031702
Harry Potter Book Moments 1.0
Thu Jul 24 10:06:37 2025
